import type { Coin } from "./types";

export const mockCoins: Coin[] = [
  {
    id: "bitcoin",
    name: "Bitcoin",
    symbol: "BTC",
    price: 42300.12,
    change24h: 3.23,
    marketCap: 830,
    volume: 24.8,
    rank: 1,
  },
  {
    id: "ethereum",
    name: "Ethereum",
    symbol: "ETH",
    price: 3009.38,
    change24h: 2.18,
    marketCap: 361,
    volume: 15.2,
    rank: 2,
  },
  {
    id: "tether",
    name: "Tether",
    symbol: "USDT",
    price: 1,
    change24h: -0.01,
    marketCap: 96,
    volume: 51.4,
    rank: 3,
  },
  {
    id: "binancecoin",
    name: "BNB",
    symbol: "BNB",
    price: 417.62,
    change24h: 1.95,
    marketCap: 64,
    volume: 1.9,
    rank: 4,
  },
  {
    id: "solana",
    name: "Solana",
    symbol: "SOL",
    price: 98.44,
    change24h: 4.82,
    marketCap: 43,
    volume: 3.7,
    rank: 5,
  },
  {
    id: "xrp",
    name: "XRP",
    symbol: "XRP",
    price: 0.81,
    change24h: -0.79,
    marketCap: 44,
    volume: 2.1,
    rank: 6,
  },
];
